### PR TITLE
Accessors and interface methods

### PR DESCRIPTION
**Pull request by mrsimpson**
@graywolf336 In order to illustrate what I meant by "accessors", find an alternative way of injecting options to retrieve data from rocket chat in the rocketlets in this PR.

### CODE REVIEW

**Comment by graywolf336** [comment]
Okay this makes sense to me and I like it.

However, there is one part that I am questioning. On the `IPreMessageSentHandler` you have now defined three methods on this interface but they have very generic names and aren't specific to the event which this interface is handling. The reason I am questioning this is because of the fact that if a Rocketlet implements another interface, such as `IPreRoomCreateHandler`, then that second one should probably have similar methods and the two would clash since in Javascript you can't do method overloading.

Would it be better to prefix the methods with the event they're handling?

**Comment by mrsimpson** [comment]
@graywolf336 Glad I could express the principle! I do not know how TS compiles interfaces (precisely interface implementations) to JS. I actually expected that for each interface, an object with functions for each interface method was compiled. But I simply do not know. 
The method names don't seem really generic to me,  I'd expect clashes actually only for "isApplicable". In the other methods, the class referred to differs (manipulateMessage vs. manipulateRoom).

**Comment by graywolf336** [comment]
@mrsimpson here is some examples:

<details>
  <summary>TypeScript Source Code (click to expand)</summary>

```
import { IMessageExtend } from 'temporary-rocketlets-ts-definition/accessors/IMessageExtend';
import { IMessageRead } from 'temporary-rocketlets-ts-definition/accessors/IMessageRead';
import { IRead } from 'temporary-rocketlets-ts-definition/accessors/IRead';
import { IMessage } from 'temporary-rocketlets-ts-definition/messages/IMessage';
import { IPreMessageSentHandler } from 'temporary-rocketlets-ts-definition/messages/IPreMessageSentHandler';
import { Rocketlet } from 'temporary-rocketlets-ts-definition/Rocketlet';

export class TestingRocketlet extends Rocketlet implements IPreMessageSentHandler {
    constructor() {
        super('Testing', 1, '0.0.1', 'Testing description.', '0.2.2');
    }

    public initialize(): void {
        throw new Error('Method not implemented.');
    }

    public onEnable(): boolean {
        throw new Error('Method not implemented.');
    }

    public onDisable(): void {
        throw new Error('Method not implemented.');
    }

    public isApplicable(message: IMessage, read: IRead): boolean {
        throw new Error('Method not implemented.');
    }

    public extendMessage(message: IMessage, read: IMessageRead, extend: IMessageExtend): void {
        throw new Error('Method not implemented.');
    }

    public manipulateMessage(message: IMessage, read: IMessageRead): IMessage {
        throw new Error('Method not implemented.');
    }
}
```

</details>

It only implements one interface.

<details>
  <summary>Compiles down into (click to expand)</summary>

```
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var Rocketlet_1 = require("temporary-rocketlets-ts-definition/Rocketlet");
var TestingRocketlet = (function (_super) {
    __extends(TestingRocketlet, _super);
    function TestingRocketlet() {
        return _super.call(this, 'Testing', 1, '0.0.1', 'Testing description.', '0.2.2') || this;
    }
    TestingRocketlet.prototype.initialize = function () {
        throw new Error('Method not implemented.');
    };
    TestingRocketlet.prototype.onEnable = function () {
        throw new Error('Method not implemented.');
    };
    TestingRocketlet.prototype.onDisable = function () {
        throw new Error('Method not implemented.');
    };
    TestingRocketlet.prototype.isApplicable = function (message, read) {
        throw new Error('Method not implemented.');
    };
    TestingRocketlet.prototype.extendMessage = function (message, read, extend) {
        throw new Error('Method not implemented.');
    };
    TestingRocketlet.prototype.manipulateMessage = function (message, read) {
        throw new Error('Method not implemented.');
    };
    return TestingRocketlet;
}(Rocketlet_1.Rocketlet));
exports.TestingRocketlet = TestingRocketlet;
//# sourceMappingURL=testing.js.map
```

</details>

So, each interface a Rocketlet implements it expects that direct class must implement each method. If we have two interfaces with the same method names it won't work. Which is why I was saying, the names of the methods are too generic if we have more than one interface which goes that route.

**Comment by graywolf336** [comment]
@mrsimpson Would you be against naming the `isApplicable` for `IPreMessageSentHandler` to `isMessageApplicable`? That way we can have `isRoomApplicable` for `IPreRoomCreateHandler` and one Rocketlet implements both interfaces?

An example of this is here: https://github.com/graywolf336/temporary-rocketlets-dev-environment/blob/65762c3cbfd8345c3601ec037c4072a6d061ca99/examples/testing.ts

**Pull request merged**
