### PR TITLE
Added generated class-diagrams

### PR DESCRIPTION
**Pull request by mrsimpson**
Generated from IntelliJ (webstorm or IDEA) - not perfect (documentation not as comment), but more visual compared to code.

WDYT?

### CODE REVIEW

**Comment by mrsimpson** [comment]
@graywolf336 seriously, I don't think the class diagrams I attached are good enough for a documentation, but maybe good enough for an internal knowledge-transfer.
I was also quite impressed by [yuml.me](https://yuml.me/diagram/scruffy/class/samples). This would also be possible to be generated from the classes / Interfaces metadata ;)

**Comment by graywolf336** [comment]
Yeah, I think the style depends on the style of the documentation website but I do like and think a UML is needed. :+1:

**Comment by graywolf336** [comment]
I say let's leave this pull request open for now, that way if anyone stumbles upon it or I can direct some people internally to view it and visualize it.

**Comment by mrsimpson** [comment]
That was the intention - you may even close it. Just thought this way it's more transparent compared to sending them to you via Skype ;)

**Comment by graywolf336** [comment]
Works for me :+1: thanks for that and more!

**Pull request closed without merging**
